package GUIMODERN;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class VtnTaxiIngreso extends javax.swing.JFrame {

    /**
     * Creates new form Ventana21
     */
    public VtnTaxiIngreso() {
        initComponents();
        bck.setBackground(new Color(0,0,0,200));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIngreso = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_usuarioTaxi = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jpssw_ContrasenaTaxi = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jbtn_IniciarSesionTaxi = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ingresoFbTaxi = new javax.swing.JLabel();
        ingresoInstagramTaxi = new javax.swing.JLabel();
        ingresoCorreoTaxi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        bck = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIngreso.setBackground(new java.awt.Color(255, 192, 5));
        panelIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(24, 24, 24));
        jLabel4.setText("USUARIO : ");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        panelIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(24, 24, 24));
        jLabel6.setText("CONTRASENA :");
        panelIngreso.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 334, -1, -1));

        jtxt_usuarioTaxi.setBackground(new java.awt.Color(255, 192, 5));
        jtxt_usuarioTaxi.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jtxt_usuarioTaxi.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_usuarioTaxi.setBorder(null);
        jtxt_usuarioTaxi.setCaretColor(new java.awt.Color(255, 255, 255));
        panelIngreso.add(jtxt_usuarioTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 250, 242, -1));
        panelIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 272, 268, 10));

        jpssw_ContrasenaTaxi.setBackground(new java.awt.Color(255, 192, 5));
        jpssw_ContrasenaTaxi.setText("jPasswordField1");
        jpssw_ContrasenaTaxi.setBorder(null);
        jpssw_ContrasenaTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpssw_ContrasenaTaxiActionPerformed(evt);
            }
        });
        panelIngreso.add(jpssw_ContrasenaTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 334, 268, 25));
        panelIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 365, 268, 20));

        jbtn_IniciarSesionTaxi.setBackground(new java.awt.Color(255, 192, 5));
        jbtn_IniciarSesionTaxi.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jbtn_IniciarSesionTaxi.setText("INICIAR SESION");
        jbtn_IniciarSesionTaxi.setBorder(null);
        jbtn_IniciarSesionTaxi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_IniciarSesionTaxiActionPerformed(evt);
            }
        });
        panelIngreso.add(jbtn_IniciarSesionTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 409, 48));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(24, 24, 24));
        jLabel5.setText("Ingreso rapido  por Redes Sociales: ");
        panelIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(24, 24, 24));
        jLabel7.setText("Si no eres miembro aun, contacta con nosotros : ");
        panelIngreso.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(24, 24, 24));
        jLabel8.setText(". : F R D W : .");
        panelIngreso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 560, 78, 26));

        jLabel9.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(24, 24, 24));
        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Facebook_20px.png")); // NOI18N
        panelIngreso.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 33, 26));

        jLabel10.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(24, 24, 24));
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Instagram_20px.png")); // NOI18N
        panelIngreso.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 33, 26));

        jLabel11.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(24, 24, 24));
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Message Filled_20px.png")); // NOI18N
        panelIngreso.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 530, -1, 26));

        ingresoFbTaxi.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ingresoFbTaxi.setForeground(new java.awt.Color(24, 24, 24));
        ingresoFbTaxi.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Facebook_20px.png")); // NOI18N
        panelIngreso.add(ingresoFbTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 47, 26));

        ingresoInstagramTaxi.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ingresoInstagramTaxi.setForeground(new java.awt.Color(24, 24, 24));
        ingresoInstagramTaxi.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Instagram_20px.png")); // NOI18N
        panelIngreso.add(ingresoInstagramTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, -1, 26));

        ingresoCorreoTaxi.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        ingresoCorreoTaxi.setForeground(new java.awt.Color(24, 24, 24));
        ingresoCorreoTaxi.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Message Filled_20px.png")); // NOI18N
        panelIngreso.add(ingresoCorreoTaxi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 38, 26));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Taxi_50px.png")); // NOI18N
        jLabel1.setText("   . : : T A X I : : . ");
        panelIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 106, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\Cancel_20px_2.png")); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        panelIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 50, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Return_20px.png")); // NOI18N
        panelIngreso.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 50, 20));

        getContentPane().add(panelIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, 590));

        bck.setBackground(new java.awt.Color(0, 0, 0));
        bck.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Drone With Camera_50px.png")); // NOI18N
        bck.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("   .::FRDW::. 1.0 ");
        bck.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Conteo, Monitoreo, Estadistica");
        bck.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        getContentPane().add(bck, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 590));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Proyecto\\APP CLIENTE SERVIDOR\\GUI MODERN\\IMG TAXI\\Atardecer-en-la-Calle-de-Alcalá.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        //System.exit(0);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jbtn_IniciarSesionTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_IniciarSesionTaxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_IniciarSesionTaxiActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jpssw_ContrasenaTaxiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpssw_ContrasenaTaxiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpssw_ContrasenaTaxiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnTaxiIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnTaxiIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnTaxiIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnTaxiIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnTaxiIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bck;
    private javax.swing.JLabel ingresoCorreoTaxi;
    private javax.swing.JLabel ingresoFbTaxi;
    private javax.swing.JLabel ingresoInstagramTaxi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtn_IniciarSesionTaxi;
    private javax.swing.JPasswordField jpssw_ContrasenaTaxi;
    private javax.swing.JTextField jtxt_usuarioTaxi;
    private javax.swing.JPanel panelIngreso;
    // End of variables declaration//GEN-END:variables
}
