--------------------------------------------------------
-- Archivo creado  - sábado-enero-12-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ENCUESTA
--------------------------------------------------------

  CREATE TABLE "ENCUESTA" 
   (	"IDENCUESTA" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"IDTIPOENCUESTA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE1_PK" ON "ENCUESTA" ("IDENCUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ENCUESTA
--------------------------------------------------------

  ALTER TABLE "ENCUESTA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
 
  ALTER TABLE "ENCUESTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "ENCUESTA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
 
  ALTER TABLE "ENCUESTA" MODIFY ("IDTIPOENCUESTA" NOT NULL ENABLE);
 
  ALTER TABLE "ENCUESTA" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("IDENCUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
