--------------------------------------------------------
-- Archivo creado  - lunes-enero-21-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESPUESTAOPCIONMULTIPLE
--------------------------------------------------------

  CREATE TABLE "RESPUESTAOPCIONMULTIPLE" 
   (	"IDRESPUESTAOPCIONMULTIPLE" NUMBER, 
	"IDPREGUNTA" NUMBER, 
	"IDENCUESTA" NUMBER, 
	"IDOPCION" NUMBER, 
	"IDUSUARIO" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.RESPUESTAOPCIONMULTIPLE
SET DEFINE OFF;
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (0,1,3,1,'d');
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (1,1,3,1,'d');
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (2,1,6,1,'0104444444');
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (3,1,8,1,'0155555555');
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (4,1,8,1,'0105596867');
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (5,4,6,9,'nombrembre');
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (6,4,6,10,'0104496765');
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (7,3,1,4,'1212121212');
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (8,3,1,5,'1111111111');
Insert into SYSTEM.RESPUESTAOPCIONMULTIPLE (IDRESPUESTAOPCIONMULTIPLE,IDPREGUNTA,IDENCUESTA,IDOPCION,IDUSUARIO) values (9,3,1,4,'aaaaaaaaa1');
--------------------------------------------------------
--  DDL for Index RESPUESTAOPCIONMULTIPLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESPUESTAOPCIONMULTIPLE_PK" ON "RESPUESTAOPCIONMULTIPLE" ("IDRESPUESTAOPCIONMULTIPLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RESPUESTAOPCIONMULTIPLE
--------------------------------------------------------

  ALTER TABLE "RESPUESTAOPCIONMULTIPLE" ADD CONSTRAINT "RESPUESTAOPCIONMULTIPLE_PK" PRIMARY KEY ("IDRESPUESTAOPCIONMULTIPLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "RESPUESTAOPCIONMULTIPLE" MODIFY ("IDRESPUESTAOPCIONMULTIPLE" NOT NULL ENABLE);
 
  ALTER TABLE "RESPUESTAOPCIONMULTIPLE" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
 
  ALTER TABLE "RESPUESTAOPCIONMULTIPLE" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
 
  ALTER TABLE "RESPUESTAOPCIONMULTIPLE" MODIFY ("IDOPCION" NOT NULL ENABLE);
 
  ALTER TABLE "RESPUESTAOPCIONMULTIPLE" MODIFY ("IDUSUARIO" NOT NULL ENABLE);
