--------------------------------------------------------
-- Archivo creado  - sábado-enero-12-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RESPUESTA
--------------------------------------------------------

  CREATE TABLE "RESPUESTA" 
   (	"IDRESPUESTA" NUMBER, 
	"IDPREGUNTA" NUMBER, 
	"RESPUESTA" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESPUESTA_PK" ON "RESPUESTA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "RESPUESTA" ADD CONSTRAINT "RESPUESTA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "RESPUESTA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
 
  ALTER TABLE "RESPUESTA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
 
  ALTER TABLE "RESPUESTA" MODIFY ("RESPUESTA" NOT NULL ENABLE);
