--------------------------------------------------------
-- Archivo creado  - sábado-enero-12-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIPORESPUESTA
--------------------------------------------------------

  CREATE TABLE "TIPORESPUESTA" 
   (	"IDTIPORESPUESTA" NUMBER, 
	"TIPORESPUESTA" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPORESPUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIPORESPUESTA_PK" ON "TIPORESPUESTA" ("IDTIPORESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIPORESPUESTA
--------------------------------------------------------

  ALTER TABLE "TIPORESPUESTA" MODIFY ("IDTIPORESPUESTA" NOT NULL ENABLE);
 
  ALTER TABLE "TIPORESPUESTA" MODIFY ("TIPORESPUESTA" NOT NULL ENABLE);
 
  ALTER TABLE "TIPORESPUESTA" ADD CONSTRAINT "TIPORESPUESTA_PK" PRIMARY KEY ("IDTIPORESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
