--------------------------------------------------------
-- Archivo creado  - sábado-enero-12-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TIPOENCUESTA
--------------------------------------------------------

  CREATE TABLE "TIPOENCUESTA" 
   (	"IDTIPOENCUESTA" NUMBER, 
	"TIPOENCUESTA" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPOENCUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TIPOENCUESTA_PK" ON "TIPOENCUESTA" ("IDTIPOENCUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIPOENCUESTA
--------------------------------------------------------

  ALTER TABLE "TIPOENCUESTA" MODIFY ("IDTIPOENCUESTA" NOT NULL ENABLE);
 
  ALTER TABLE "TIPOENCUESTA" MODIFY ("TIPOENCUESTA" NOT NULL ENABLE);
 
  ALTER TABLE "TIPOENCUESTA" ADD CONSTRAINT "TIPOENCUESTA_PK" PRIMARY KEY ("IDTIPOENCUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
