/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Class.Customer;
import Class.Employee;
import Class.Product;
import Class.SaleStoreService;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

/**
 *
 * @author Ismael
 */
public class CajeroMarket extends javax.swing.JDialog {

    /**
     * Creates new form CajeroMarket
     */
     private Principal vPrincipal = (Principal)this.getParent();
     
     private Product productoV;
     private Employee empleado;
     private Customer clientito;
     private SaleStoreService venta;
     public int cajero_numero=1,m =1,p = 0,auxiliar,aux;
     private double total = 0;
     
    public CajeroMarket(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
     public void rellenar(){
      int n = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().size();
        this.codigo.setText(String.valueOf(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().size()) + 1);
        
        for(int i = 0; i <  n; i++){
            this.empleados.addItem(vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(i).toString());
        }
        
        n = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().size();
        JOptionPane.showMessageDialog(null, "total Productos: " + n);
        for(int i = 0; i <  n; i++){
            this.productos.addItem(vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(i).toString());
        }
    }
     
     public void limpiarProducto(){
         this.jTextField6.setText("");
         this.jTextField7.setText("");
         this.jTextField9.setText("");
         this.modProducto.setEnabled(false);
        this.aregarProducto.setEnabled(true);
     }
     
     public void limpiarEmployee(){
        this.jTextField10.setText("");
        this.jTextField11.setText("");
        this.jTextField12.setText("");
        this.jTextField13.setText("");
        this.agregarEmpleado.setEnabled(true);
        this.modEmpleado.setEnabled(false);
     }
     
      public void limpiarVenta(){
        this.jTextField18.setEditable(true);
        this.jTextField1.setText("0");
        this.jTextField15.setText("");
        this.jTextField16.setText("");
        this.jTextField17.setText("");
        this.jTextField8.setText("");
        this.modCliente.setEnabled(false);
        this.jTextField18.setText("");
        listModel.removeAllElements();
        listModel2.removeAllElements();
        listModel3.removeAllElements();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        modCliente = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        productos = new javax.swing.JComboBox();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listModel2 = new DefaultListModel();
        jList2 = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        listModel3 = new DefaultListModel();
        jList3 = new javax.swing.JList();
        jTextField8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        empleados = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        listModel = new DefaultListModel();
        jList4 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        aregarProducto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        agregarEmpleado = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        buscarCombustible = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        modProducto = new javax.swing.JButton();
        buscarEmpleado = new javax.swing.JButton();
        modEmpleado = new javax.swing.JButton();
        nuevoCombustible = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel3.setBackground(new java.awt.Color(237, 75, 237));

        jButton3.setText("AUTOCOMPLETADO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setText("NOMBRE:");

        jTextField15.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField15.setText("Manuel Arevalo");
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField15KeyTyped(evt);
            }
        });

        jLabel12.setText("DIRECCION:");

        jTextField16.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField16.setText("Av Americas y Mariano Cueva");

        jLabel19.setText("CORREO:");

        jTextField17.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField17.setText("manuel15@hotmail.com");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/venta-de-etiqueta-icono-7489-64.png"))); // NOI18N
        jButton4.setText("VENDER");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        modCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/modificar.png"))); // NOI18N
        modCliente.setText("MODIFICAR");
        modCliente.setBorder(null);
        modCliente.setBorderPainted(false);
        modCliente.setContentAreaFilled(false);
        modCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modCliente.setEnabled(false);
        modCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modClienteActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/limpiar.png"))); // NOI18N
        jButton6.setText("NUEVO");
        jButton6.setBorder(null);
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel21.setText("CEDULA:");

        jTextField18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField18.setText("0115148786");
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField18KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton3))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(modCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(modCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(3, 3, 3))))
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );

        jLabel1.setText("PRODUCTO: ");

        jButton7.setText("AGREAGAR A LA LISTA");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel2.setText("TOTAL A PAGAR:");

        jButton9.setText("REPORTE VENTAS");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("LCD", 0, 48)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jList2.setModel(listModel2);
        jScrollPane2.setViewportView(jList2);

        jList3.setModel(listModel3);
        jScrollPane3.setViewportView(jList3);

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setText("2");

        jLabel7.setText("CANTIDAD:");

        jLabel4.setText("EMPLEADO:");

        jList4.setModel(listModel);
        jScrollPane4.setViewportView(jList4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(empleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(productos, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(217, 63, 198));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("LAS OPCIONES AGRAGAR Y MODIFICAR EN ESTE PANEL");

        aregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/agregar.png"))); // NOI18N
        aregarProducto.setText("AGRAGAR PRODUCTO");
        aregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aregarProductoActionPerformed(evt);
            }
        });

        jLabel10.setText("DETALLE PRODUCTO:");

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("COCA COLA");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jLabel11.setText("COSTO UNITARIO:");

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setText("1");
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LO REALIZAN EL GERENTE O LA ADMINISRTACION");

        jLabel14.setText("EXISTENTES:");

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField9.setText("15");
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        agregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/agregar.png"))); // NOI18N
        agregarEmpleado.setText("AGREGAR EMPLEADO");
        agregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpleadoActionPerformed(evt);
            }
        });

        jLabel15.setText("CEDULA EMPLEADO:");

        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField10.setText("0102876123");
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jLabel16.setText("NOMBRE EMPLEADO:");

        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField11.setText("Maldonado Perez");
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jLabel17.setText("DIRECCION EMP:");

        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField12.setText("Rio Palurmo y Pereira esquina");

        jLabel18.setText("CORREO EMPLEADO");

        buscarCombustible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/jf.png"))); // NOI18N
        buscarCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCombustibleActionPerformed(evt);
            }
        });

        jTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField13.setText("pereza@hotmail.es");

        modProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/documento-de-modificar-el-archivo-de-papel-icono-4468-32.png"))); // NOI18N
        modProducto.setToolTipText("");
        modProducto.setEnabled(false);
        modProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modProductoActionPerformed(evt);
            }
        });

        buscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/jf.png"))); // NOI18N
        buscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEmpleadoActionPerformed(evt);
            }
        });

        modEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/documento-de-modificar-el-archivo-de-papel-icono-4468-32.png"))); // NOI18N
        modEmpleado.setToolTipText("");
        modEmpleado.setEnabled(false);
        modEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modEmpleadoActionPerformed(evt);
            }
        });

        nuevoCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCombustibleActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setText("CODIGO ( numero total de productos + 1 ):");

        codigo.setEditable(false);
        codigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        codigo.setText("1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField10)
                            .addComponent(jTextField11)
                            .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(jTextField13)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(agregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscarEmpleado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modEmpleado)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(aregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuevoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField6))))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aregarProducto)
                    .addComponent(buscarCombustible)
                    .addComponent(modProducto)
                    .addComponent(nuevoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buscarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarEmpleado))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aregarProductoActionPerformed
        
        int p = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE LA CEDULA DEL ADMINISTRADOR DE ESTA SUCURSAL\nO INGRESE LA CEDULA DEL GERENTE","ALTO!!! IDENTIFIQUESE",3));
        if(p == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getRuc() ||  p == this.vPrincipal.nuevoGerente.getRuc()){
         
            if( jTextField6.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"INGRESE EL DETALLE DEL PRODUCTO","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField7.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null,"INGRESE EL COSTO POR UNIDAD DEL PRODUCTO","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField9.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"INGRESE EL TOTAL DE UNIDADES DEL PRODUCTO EXISTENTES","ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
                int o = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().size();
                this.productoV = new Product(Integer.parseInt(this.codigo.getText()),Double.parseDouble(this.jTextField7.getText()),Integer.parseInt(this.jTextField9.getText()),this.jTextField6.getText());
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).createProduct(productoV);
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(o).seeInfo();
                this.productos.addItem(this.productoV.toString());
                
                this.codigo.setText(String.valueOf(Integer.parseInt(this.codigo.getText()) + 1));
                
                limpiarProducto();
            }
        }else{
            JOptionPane.showMessageDialog(null,"LA CEDULA NO CORRESPONDE AL USUARIO ADMINSTRADOR DE ESTE BOTON","ERROR DE AUNTENTICIDAD",JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_aregarProductoActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ' ) evt.consume();
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        char c = evt.getKeyChar();
        if((c < '0' || c > '9') && c != '.' ) evt.consume();
        //if((c >= 'a' && c <= 'z') || (c > 'A' && c < 'Z') || c == ' ' ) evt.consume();
    }//GEN-LAST:event_jTextField7KeyTyped

    private void agregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpleadoActionPerformed
 
        int h = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE LA CEDULA DEL ADMINISTRADOR DE ESTA SUCURSAL\nO INGRESE LA CEDULA DEL GERENTE","ALTO!!! IDENTIFIQUESE",3));
        if(h == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getRuc() ||  h == this.vPrincipal.nuevoGerente.getRuc()){
         
        if( jTextField10.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"EL RUC NO ESTA COMPLETADO","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField11.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null,"NOMBRE SIN LLENAR","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField12.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"COMPLETE EL CAMPO DE DIRECCION","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField13.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null,"COMPLETE EL CAMPO CORREO","ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
                int o = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().size();
                this.empleado =  new Employee("CAJERO N" + cajero_numero + " MINIMARKET",Integer.parseInt(jTextField10.getText()),jTextField11.getText(),jTextField12.getText(),jTextField13.getText());
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).createEmployee(empleado);
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(o).seeInfo();
                this.empleados.addItem(this.empleado.toString());
                this.limpiarEmployee();
                this.modEmpleado.setEnabled(false);
            }   
        }else{
            JOptionPane.showMessageDialog(null,"LA CEDULA NO CORRESPONDE AL USUARIO ADMINSTRADOR DE ESTE BOTON","ERROR DE AUNTENTICIDAD",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarEmpleadoActionPerformed

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9' ) evt.consume();
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ') evt.consume();
    }//GEN-LAST:event_jTextField11KeyTyped

    private void buscarCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCombustibleActionPerformed
        p = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE EL CODIGO DEL PRODUCTO","BUSCANDO",3));
        int y = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().size();
        
        if(p < 1 || p > y){
            JOptionPane.showMessageDialog(null,"NO EXISTE ESE PRODUCTO","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            
            this.jTextField6.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(p-1).getDescripcion());
            this.jTextField7.setText(String.valueOf(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(p-1).getCostoUnitario()));
            this.jTextField9.setText(String.valueOf(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(p-1).getExistencia()));
            this.modProducto.setEnabled(true);
            this.aregarProducto.setEnabled(false);
            }
    }//GEN-LAST:event_buscarCombustibleActionPerformed

    private void nuevoCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCombustibleActionPerformed
        limpiarProducto();
    }//GEN-LAST:event_nuevoCombustibleActionPerformed

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9' ) evt.consume();
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().size();
        for(int j = 0; j < i; j ++){
            if(Integer.parseInt(this.jTextField18.getText()) == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(j).getRuc()){
                this.jTextField15.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(j).getNombre());
                this.jTextField16.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(j).getDireccion());
                this.jTextField17.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(j).getCorreo());
                this.jTextField18.setEditable(false);
                this.modCliente.setEnabled(true);
                aux = j;
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyTyped
        char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ' ) evt.consume();
    }//GEN-LAST:event_jTextField15KeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int yolo = 0;
            if( jTextField18.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"INGRESE LA CEDULA DEL CLIENTE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField15.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null,"INGRESE EL NOMBRE DEL CLIENTE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField16.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"INGRESE LA DIRECCION DEL CLIENTE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField17.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"INGRESE EL CORREO DEL CLIENTE","ERROR",JOptionPane.ERROR_MESSAGE);
            }/*else if(Integer.parseInt(jTextField1.getText()) == 0) {
                JOptionPane.showMessageDialog(null,"REALIZE ALGUNA COMPRA","ERROR",JOptionPane.ERROR_MESSAGE);
            }*/else if(productos.getActionCommand().isEmpty() ){
                JOptionPane.showMessageDialog(null,"ESTE DISPENSADOR NO TIENE PRODUCTOS... AGREGELOS","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(empleados.getActionCommand().isEmpty() ){
                JOptionPane.showMessageDialog(null,"ESTE DISPENSADOR NO TIENE EMPLEADO TRABAJANDO.. AGREGELOS","ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
                int i = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().size();
                for(int j = 0; j < i; j++){
                    if(Integer.parseInt(this.jTextField18.getText()) == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(j).getRuc()){
                        this.clientito = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(j);
                        yolo = 1;
                    }
                }
                if(yolo == 0){
                    //int y = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().size();
                    this.clientito = new Customer(Integer.parseInt(this.jTextField18.getText()),this.jTextField15.getText(),this.jTextField16.getText(),this.jTextField17.getText());
                    this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).createCustomer(clientito);
                    this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(i).seeInfo();                    
                }
                /* productos    
                i = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().size();
                for(int j = 0; j < i; j ++){
                    if(this.jComboBox1.getSelectedItem().toString().equals(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(j).getNombre())){
                        auxiliar = j;
                        this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(j).setOctanaje(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(j).getOctanaje() - Integer.parseInt(this.jTextField1.getText()));
                        this.combustibleV = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(j);
                    }
                }*/
                
                               
                i = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().size();
                    
                for(int j = 0; j < i; j++){
                   
                    if(this.empleados.getSelectedItem().toString().equalsIgnoreCase(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(j).getNombre())){
                   
                        this.empleado = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(j);
                        this.empleado.seeInfo();
                    }
                } 
                
                int ultimaVenta = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getVenta().size();
                
                venta = new SaleStoreService(clientito,empleado,Double.parseDouble(this.jTextField1.getText()));
                this.vPrincipal.nuevoGerente.createSaleStoreService(venta);
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).createSaleStoreService(venta);
                
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getVenta().get(ultimaVenta).sale();
                this.limpiarVenta();
                
            }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void modClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modClienteActionPerformed
        this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(aux).setNombre(this.jTextField15.getText());
        this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(aux).setDireccion(this.jTextField16.getText());
        this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getClientes().get(aux).setCorreo(this.jTextField17.getText());
        JOptionPane.showMessageDialog(null, "CLIENTE MODIFICADADO EXITOSAMENTE","ESTADO CLIENTE",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_modClienteActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField18KeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void modProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modProductoActionPerformed
        int h = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE LA CEDULA DEL ADMINISTRADOR DE ESTA SUCURSAL\nO INGRESE LA CEDULA DEL GERENTE","ALTO!!! IDENTIFIQUESE",3));
        if(h == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getRuc() ||  p == this.vPrincipal.nuevoGerente.getRuc()){
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(p-1).setDescripcion(this.jTextField6.getText());
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(p-1).setCostoUnitario(Integer.parseInt(this.jTextField7.getText()));
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(p-1).setExistencia(Integer.parseInt(this.jTextField9.getText()));         
        }else{
            JOptionPane.showMessageDialog(null,"CODIGO INCORRECTO","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        this.modProducto.setEnabled(false);
        this.aregarProducto.setEnabled(true);
    }//GEN-LAST:event_modProductoActionPerformed

    private void buscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEmpleadoActionPerformed
        int h = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE EL NUMERO DE CEDULA DEL EMPLEADO","BUSCANDO",3));
        int y = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().size();
        for(int i = 0; i < y; i++){
            
            if(h == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(i).getRuc()){
                this.jTextField10.setText(String.valueOf(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(i).getRuc()));
                this.jTextField11.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(i).getNombre());
                this.jTextField12.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(i).getDireccion());
                this.jTextField13.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(i).getCorreo());
                this.modEmpleado.setEnabled(true);
                this.agregarEmpleado.setEnabled(false);
                auxiliar = i;
            }

        }
    }//GEN-LAST:event_buscarEmpleadoActionPerformed

    private void modEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modEmpleadoActionPerformed
        int h = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE LA CEDULA DEL ADMINISTRADOR DE ESTA SUCURSAL\nO INGRESE LA CEDULA DEL GERENTE","ALTO!!! IDENTIFIQUESE",3));
        if(h == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getRuc() ||  p == this.vPrincipal.nuevoGerente.getRuc()){
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(auxiliar).setNombre(this.jTextField11.getText());    
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(auxiliar).setDireccion(this.jTextField12.getText());  
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getEmpleados().get(auxiliar).setCorreo(this.jTextField13.getText());      
        }else{
            JOptionPane.showMessageDialog(null,"CODIGO INCORRECTO","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        this.modEmpleado.setEnabled(false);
        this.agregarEmpleado.setEnabled(true);
    }//GEN-LAST:event_modEmpleadoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if( jTextField8.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"INDIQUE LA CANTIDAD DEL PRODCUTO A ADQUIRIR","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
            
            int cantidad =  Integer.parseInt(this.jTextField8.getText());
            for(int i = 0; i < this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().size();i++){
                if(this.productos.getSelectedItem().toString().equalsIgnoreCase(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(i).getDescripcion())){
                    
                this.total = total + (cantidad * this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(i).getCostoUnitario());
                    
                    listModel.addElement(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(i).getCodigo());
                    listModel2.addElement(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(i).getDescripcion());
                    listModel3.addElement(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getProductos().get(i).getCostoUnitario() * cantidad);
                    
                    this.jTextField1.setText(String.valueOf(total));
                
                }           
            }
        }    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       this.vPrincipal.reportesCajeroM(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(cajero_numero-1).getVenta().size(), cajero_numero, m);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.limpiarEmployee();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajeroMarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajeroMarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajeroMarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajeroMarket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CajeroMarket dialog = new CajeroMarket(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEmpleado;
    private javax.swing.JButton aregarProducto;
    private javax.swing.JButton buscarCombustible;
    private javax.swing.JButton buscarEmpleado;
    private javax.swing.JTextField codigo;
    private javax.swing.JComboBox empleados;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList2;
    private DefaultListModel listModel2;
    private javax.swing.JList jList3;
    private DefaultListModel listModel3;
    private javax.swing.JList jList4;
    private DefaultListModel listModel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton modCliente;
    private javax.swing.JButton modEmpleado;
    private javax.swing.JButton modProducto;
    private javax.swing.JButton nuevoCombustible;
    private javax.swing.JComboBox productos;
    // End of variables declaration//GEN-END:variables
}
