/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Class.CustomerServiceStation;
import Class.EmployeeServiceStation;
import Class.Fuel;
import Class.saleServiceStation;
import static Interface.Sucursal.i;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Ismael
 */
public class Dispensador extends javax.swing.JDialog {

    /**
     * Creates new form Dispensador
     */
    private Fuel combustibleV;
    private CustomerServiceStation clientito;
    private EmployeeServiceStation empleado;
    private saleServiceStation venta;
    
    private Principal vPrincipal = (Principal)this.getParent();
    public int dispensador_numero=1,m =1,aux = 0,numerito = 0,auxiliar,auxiliar1;
    
    public Dispensador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.jComboBox2.addItem("GASOLINA");
        this.jComboBox2.addItem("DIESEL");

    }
    public void rellenar(){
        int n = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().size();
        JOptionPane.showMessageDialog(null, "total gasolinas: " + n);
        this.num.setText(String.valueOf(n));
        
        for(int i = 0; i <  n; i++){
            this.jComboBox1.addItem(vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(i).toString());
        }
        n = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().size();
        for(int i = 0; i <  n; i++){
            this.jComboBox3.addItem(vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(i).toString());
        }
    }
    
    public void limpiarFuel(){
        this.jTextField6.setText("");
        this.jTextField7.setText("");
        this.jTextField9.setText("");
        this.aregarCombustible.setEnabled(true);
        this.modCombustible.setEnabled(false);
    }
    public void limpiarEmployee(){
        this.jTextField10.setText("");
        this.jTextField11.setText("");
        this.jTextField12.setText("");
        this.jTextField13.setText("");
        this.agregarEmpleado.setEnabled(true);
        this.modEmpleado.setEnabled(false);
    }
    public void limpiarVenta(){
        this.jTextField2.setEditable(true);
        this.jTextField1.setText("");
        this.jTextField2.setText("");
        this.jTextField3.setText("");
        this.jTextField4.setText("");
        this.jTextField5.setText("");
        this.jTextField14.setText("");
    }
    public static String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYY");
        return formatoFecha.format(fecha);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        modCliente = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        aregarCombustible = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        agregarEmpleado = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        buscarCombustible = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        modCombustible = new javax.swing.JButton();
        buscarEmpleado = new javax.swing.JButton();
        modEmpleado = new javax.swing.JButton();
        nuevoCombustible = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel2.setBackground(new java.awt.Color(255, 205, 0));

        jLabel1.setText("GALONES:");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel3.setText("PLACAS:");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("AFD0612");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("AUTOCOMPLETADO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("NOMBRE:");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField3.setText("Manuel Arevalo");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField3KeyTyped(evt);
            }
        });

        jLabel5.setText("DIRECCION:");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setText("Av Americas y Mariano Cueva");

        jLabel6.setText("CORREO:");

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("manuel15@hotmail.com");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/venta-de-etiqueta-icono-7489-64.png"))); // NOI18N
        jButton2.setText("VENDER");
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        modCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/modificar.png"))); // NOI18N
        modCliente.setText("MODIFICAR");
        modCliente.setBorder(null);
        modCliente.setBorderPainted(false);
        modCliente.setContentAreaFilled(false);
        modCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modCliente.setEnabled(false);
        modCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        modCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        modCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modClienteActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/limpiar.png"))); // NOI18N
        jButton5.setText("NUEVO");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel20.setText("CEDULA:");

        jTextField14.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField14.setText("0115148786");
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField14KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(modCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(32, 32, 32)
                                .addComponent(jTextField5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel20))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jTextField2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1))
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField14))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(14, 14, 14))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jLabel2.setText("NOMBRE DE COMBUSTIBLE:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel11.setText("NUMERO DE COMBUSTIBLES:");

        num.setEditable(false);
        num.setBackground(new java.awt.Color(255, 230, 0));
        num.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        num.setText("0");
        num.setBorder(null);
        num.setEnabled(false);

        jLabel13.setText("TOTAL A PAGAR:");

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("LCD", 0, 60)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setText("12.15");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel19.setText("ENCARGADO DE TURNO:");

        jButton3.setText("REPORTE VENTAS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel19))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(num)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 156, 0));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("LAS OPCIONES AGRAGAR Y MODIFICAR EN ESTE PANEL");

        aregarCombustible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/agregar.png"))); // NOI18N
        aregarCombustible.setText("AGRAGAR COMBUSTIBLE");
        aregarCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aregarCombustibleActionPerformed(evt);
            }
        });

        jLabel8.setText("TIPO DE COMBUSTIBLE:");

        jLabel9.setText("NOMBRE COMBUSTIBLE:");

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("Super");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jLabel10.setText("COSTO POR GALO:");

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setText("2");
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("LO REALIZAN EL GERENTE O LA ADMINISRTACION");

        jLabel14.setText("G EXISTENTES:");

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField9.setText("20000");
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        agregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/agregar.png"))); // NOI18N
        agregarEmpleado.setText("AGREGAR EMPLEADO");
        agregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarEmpleadoActionPerformed(evt);
            }
        });

        jLabel15.setText("CEDULA EMPLEADO:");

        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField10.setText("0102876123");
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jLabel16.setText("NOMBRE EMPLEADO:");

        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField11.setText("Maldonado Perez");
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jLabel17.setText("DIRECCION EMP:");

        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField12.setText("Rio Palurmo y Pereira esquina");

        jLabel18.setText("CORREO EMPLEADO");

        buscarCombustible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/jf.png"))); // NOI18N
        buscarCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarCombustibleActionPerformed(evt);
            }
        });

        jTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField13.setText("pereza@hotmail.es");

        modCombustible.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/documento-de-modificar-el-archivo-de-papel-icono-4468-32.png"))); // NOI18N
        modCombustible.setToolTipText("");
        modCombustible.setEnabled(false);
        modCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modCombustibleActionPerformed(evt);
            }
        });

        buscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/jf.png"))); // NOI18N
        buscarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarEmpleadoActionPerformed(evt);
            }
        });

        modEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/documento-de-modificar-el-archivo-de-papel-icono-4468-32.png"))); // NOI18N
        modEmpleado.setToolTipText("");
        modEmpleado.setEnabled(false);
        modEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modEmpleadoActionPerformed(evt);
            }
        });

        nuevoCombustible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoCombustibleActionPerformed(evt);
            }
        });

        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(aregarCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nuevoCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField6))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17)
                                .addComponent(jLabel15))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField10)
                                .addComponent(jTextField11)
                                .addComponent(jTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                                .addComponent(jTextField13)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(agregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(buscarEmpleado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(modEmpleado)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(aregarCombustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buscarCombustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modCombustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nuevoCombustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buscarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void aregarCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aregarCombustibleActionPerformed
      int y = Integer.parseInt(this.num.getText()); 

      if(y >= 4){
          JOptionPane.showMessageDialog(null,"LO SIENTO SOLO PUEDES INGRESAR HASTA 4 COMBUSTIBLES POR DISPENSADOR","ERROR",JOptionPane.ERROR_MESSAGE);
        }else{
           int p = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE LA CEDULA DEL ADMINISTRADOR DE ESTA SUCURSAL\nO INGRESE LA CEDULA DEL GERENTE","ALTO!!! IDENTIFIQUESE",3));
        if(p == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getRuc() ||  p == this.vPrincipal.nuevoGerente.getRuc()){
         
            if( jTextField6.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"EL NOMBRE DEL COMBUSTIBLE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField7.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null,"INGRESE EL COSTO POR GALON DEL PRODUCTO","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField9.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"INGRESE EL TOTAL DE GALONES QUE EXISTEN EN PRODUCCION","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jComboBox2.getActionCommand().isEmpty() ){
                JOptionPane.showMessageDialog(null,"ELIJA UNA OPCION EN TIPO DE COMBUSTIBLE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
                this.combustibleV = new Fuel(Integer.parseInt(jTextField9.getText()),Double.parseDouble(jTextField7.getText()),this.jComboBox2.getSelectedItem().toString(),jTextField6.getText(),this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1));
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).createFuel(combustibleV);
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(y).seeInfo();
                this.jComboBox1.addItem(this.combustibleV.toString());
                this.num.setText(String.valueOf(Integer.parseInt(this.num.getText()) + 1));
                this.modCombustible.setEnabled(false);
                limpiarFuel();
            }
        }else{
            JOptionPane.showMessageDialog(null,"LA CEDULA NO CORRESPONDE AL USUARIO ADMINSTRADOR DE ESTE BOTON","ERROR DE AUNTENTICIDAD",JOptionPane.ERROR_MESSAGE);
        }
      } 
    }//GEN-LAST:event_aregarCombustibleActionPerformed

    private void agregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarEmpleadoActionPerformed
//        int y = Integer.parseInt(this.num.getText()); 
        int p = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE LA CEDULA DEL ADMINISTRADOR DE ESTA SUCURSAL\nO INGRESE LA CEDULA DEL GERENTE","ALTO!!! IDENTIFIQUESE",3));
        if(p == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getRuc() ||  p == this.vPrincipal.nuevoGerente.getRuc()){
         
        if( jTextField10.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"EL NOMBRE DEL COMBUSTIBLE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField11.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null,"INGRESE EL COSTO POR GALON DEL PRODUCTO","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField12.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"COMPLETE EL CAMPO ","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField13.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null,"COMPLETE EL CAMPO CORREO","ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
                int o = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().size();
                this.empleado =  new EmployeeServiceStation(Integer.parseInt(jTextField10.getText()),jTextField11.getText(),jTextField12.getText(),jTextField13.getText(),this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1),"Gasolinera, dispensador  " + dispensador_numero);
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).createEmployeeServiceStation(empleado);
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(o).seeInfo();
                this.jComboBox3.addItem(this.empleado.toString());
                this.limpiarEmployee();
                this.modEmpleado.setEnabled(false);
            }   
        }else{
            JOptionPane.showMessageDialog(null,"LA CEDULA NO CORRESPONDE AL USUARIO ADMINSTRADOR DE ESTE BOTON","ERROR DE AUNTENTICIDAD",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarEmpleadoActionPerformed

    private void nuevoCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoCombustibleActionPerformed
        this.limpiarFuel();
    }//GEN-LAST:event_nuevoCombustibleActionPerformed

    private void buscarCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarCombustibleActionPerformed
        String p = JOptionPane.showInputDialog(null, "INGRESE EL NOMBRE DEL COMBUSTIBLE","BUSCANDO",3);
        int y = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().size();
        for(int i = 0; i < y; i++){
            
            if(p.equalsIgnoreCase(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(i).getNombre())){
            this.jTextField6.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(i).getNombre());
            this.jTextField7.setText(String.valueOf(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(i).getCostoGalon()));
            this.jTextField9.setText(String.valueOf(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(i).getOctanaje()));
            this.modCombustible.setEnabled(true);
            this.aregarCombustible.setEnabled(false);
            auxiliar = i;
            }

            }
         
    }//GEN-LAST:event_buscarCombustibleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().size();
        for(int j = 0; j < i; j ++){
            if(this.jTextField2.getText().equals(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(j).getVehiclePlates())){
                this.jTextField3.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(j).getNombre());
                this.jTextField4.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(j).getDireccion());
                this.jTextField5.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(j).getCorreo());
                this.jTextField14.setText(String.valueOf(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(j).getRuc()));
                this.jTextField2.setEditable(false);
                this.modCliente.setEnabled(true);
                aux = j;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void modClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modClienteActionPerformed
        this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(aux).setRuc(Integer.parseInt(this.jTextField14.getText()));
        this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(aux).setNombre(this.jTextField3.getText());
        this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(aux).setDireccion(this.jTextField4.getText());
        this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(aux).setCorreo(this.jTextField5.getText());
        JOptionPane.showMessageDialog(null, "CLIENTE MODIFICADADO EXITOSAMENTE","ESTADO CLIENTE",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_modClienteActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        limpiarVenta();
        this.jTextField2.setEditable(true);
        this.modEmpleado.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int yolo = 0;
            if( jTextField1.getText().isEmpty()){
                JOptionPane.showMessageDialog(null,"INGRESE LA CANTIDAD DE GALONES","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField2.getText().isEmpty() ){
                JOptionPane.showMessageDialog(null,"INGRESE LAS PLACAS DEL VEHICULO","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField3.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"INGRESE EL NOMBRE DEL CLIENTE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField4.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"INGRESE LA DIRECCION DEL CLIENTE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField5.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"INGRESE EL CORREO DEL CLIENTE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jTextField14.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"INGRESE LA CEDULA DEL CLIENTE","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jComboBox1.getActionCommand().isEmpty() ){
                JOptionPane.showMessageDialog(null,"ESTE DISPENSADOR NO TIENE COMBUSTIBLES DISPONEBLES.. AGREGELOS","ERROR",JOptionPane.ERROR_MESSAGE);
            }else if(jComboBox3.getActionCommand().isEmpty() ){
                JOptionPane.showMessageDialog(null,"ESTE DISPENSADOR NO TIENE EMPLEADO TRABAJANDO.. AGREGELOS","ERROR",JOptionPane.ERROR_MESSAGE);
            }else{
                int i = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().size();
                for(int j = 0; j < i; j++){
                    if(this.jTextField2.getText().equals(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(j).getVehiclePlates())){
                        this.clientito = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(j);
                        yolo = 1;
                    }
                }
                if(yolo == 0){
                    //int y = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().size();
                    this.clientito = new CustomerServiceStation(Integer.parseInt(this.jTextField14.getText()),this.jTextField3.getText(),this.jTextField4.getText(),this.jTextField5.getText(),this.jTextField2.getText(),this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0));
                    this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).createCustomerServiceStation(clientito);
                    this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getClientes().get(i).seeInfo();                    
                }

                i = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().size();
                for(int j = 0; j < i; j++){
                    if(this.jComboBox1.getSelectedItem().toString().equals(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(j).getNombre())){
                        auxiliar = j;
                        this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(j).setOctanaje(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(j).getOctanaje() - Integer.parseInt(this.jTextField1.getText()));
                        this.combustibleV = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(j);
                    }
                }
                
                if(this.combustibleV.getOctanaje() >= 0){
                
                this.jTextField8.setText(String.valueOf(Integer.parseInt(this.jTextField1.getText())*this.combustibleV.getCostoGalon()));
                
                i = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().size();
                for(int j = 0; j < i; j++){
                    if(this.jComboBox3.getSelectedItem().toString().equals(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(j).getNombre())){
                        this.empleado = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(j);
                    }
                }
                numerito = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getVenta().size();
                
                venta = new saleServiceStation(empleado,clientito,combustibleV,fecha(),Integer.parseInt(this.jTextField1.getText()));
                this.vPrincipal.nuevoGerente.createSaleServiceStation(venta);
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).createSaleServiceStation(venta);
                
                this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getVenta().get(numerito).sale();
                this.limpiarVenta();
                }else{
                    this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(auxiliar).setOctanaje(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(auxiliar).getOctanaje() + Integer.parseInt(this.jTextField1.getText()));
                    JOptionPane.showMessageDialog(null,"LO SIENTO ESTE DISPENSADOR YA NO CUENTA CON SUFICIENTE COMBUSTIBLE","ERROR",JOptionPane.ERROR_MESSAGE);
                }
            }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.vPrincipal.reportesDispensador(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getVenta().size(), dispensador_numero, m);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        char c = evt.getKeyChar();
        if((c < '0' || c > '9') && c != '.') evt.consume();
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9' ) evt.consume();
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9' ) evt.consume();
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9' ) evt.consume();
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9' ) evt.consume();
    }//GEN-LAST:event_jTextField14KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
         char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c < 'A' && c > 'Z') && c != ' ') evt.consume();
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') ) evt.consume();
    }//GEN-LAST:event_jTextField11KeyTyped

    private void jTextField3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyTyped
         char c = evt.getKeyChar();
        if((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && c != ' ') evt.consume();
    }//GEN-LAST:event_jTextField3KeyTyped

    private void modCombustibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modCombustibleActionPerformed
        int p = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE LA CEDULA DEL ADMINISTRADOR DE ESTA SUCURSAL\nO INGRESE LA CEDULA DEL GERENTE","ALTO!!! IDENTIFIQUESE",3));
        if(p == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getRuc() ||  p == this.vPrincipal.nuevoGerente.getRuc()){
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(auxiliar).setNombre(this.jTextField6.getText());
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(auxiliar).setCostoGalon(Double.parseDouble(this.jTextField7.getText()));
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getCombustible().get(auxiliar).setOctanaje(Integer.parseInt(this.jTextField9.getText()));         
        }else{
            JOptionPane.showMessageDialog(null,"CODIGO INCORRECTO","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        this.modCombustible.setEnabled(false);
        this.aregarCombustible.setEnabled(true);  
    }//GEN-LAST:event_modCombustibleActionPerformed

    private void buscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarEmpleadoActionPerformed
        int p = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE EL NUMERO DE CEDULA DEL EMPLEADO","BUSCANDO",3));
        int y = this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().size();
        for(int i = 0; i < y; i++){
            
            if(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(i).getRuc() == p){
                this.jTextField10.setText(String.valueOf(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(i).getRuc()));
                this.jTextField11.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(i).getNombre());
                this.jTextField12.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(i).getDireccion());
                this.jTextField13.setText(this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(i).getCorreo());
                this.modEmpleado.setEnabled(true);
                this.agregarEmpleado.setEnabled(false);
                auxiliar1 = i;
            }

        }
    }//GEN-LAST:event_buscarEmpleadoActionPerformed

    private void modEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modEmpleadoActionPerformed
        int p = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE LA CEDULA DEL ADMINISTRADOR DE ESTA SUCURSAL\nO INGRESE LA CEDULA DEL GERENTE","ALTO!!! IDENTIFIQUESE",3));
        if(p == this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getRuc() ||  p == this.vPrincipal.nuevoGerente.getRuc()){
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(auxiliar1).setNombre(this.jTextField11.getText());    
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(auxiliar1).setDireccion(this.jTextField12.getText());  
           this.vPrincipal.nuevoGerente.getSucursales().get(m-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(dispensador_numero-1).getEmpleados().get(auxiliar1).setCorreo(this.jTextField13.getText());      
        }else{
            JOptionPane.showMessageDialog(null,"CODIGO INCORRECTO","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        this.modEmpleado.setEnabled(false);
        this.agregarEmpleado.setEnabled(true);
         
    }//GEN-LAST:event_modEmpleadoActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            this.limpiarEmployee();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dispensador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dispensador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dispensador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dispensador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dispensador dialog = new Dispensador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarEmpleado;
    private javax.swing.JButton aregarCombustible;
    private javax.swing.JButton buscarCombustible;
    private javax.swing.JButton buscarEmpleado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton modCliente;
    private javax.swing.JButton modCombustible;
    private javax.swing.JButton modEmpleado;
    private javax.swing.JButton nuevoCombustible;
    private javax.swing.JTextField num;
    // End of variables declaration//GEN-END:variables
}
