package Interface;

import Class.Box;
import Class.Company;
import Class.Dispenser;
import Class.Manager;
import Class.MechanicalService;
import Class.ServiceStation;
import Class.StoreService;
import Class.saleServiceStation;
import java.awt.BorderLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

   
    public Company nuevaEmpresa;
    public Manager nuevoGerente;
    public ServiceStation GasolineraV;
    public Dispenser dispensadorV;
    public StoreService tiendaV;
    public Box cajaV;
    public MechanicalService tecniV;
    
    
    
    public int numSucursal = 1;
    
    public Principal() {
        initComponents();    
    }
    
    public void nombramiento(){
        this.nomEmpresa.setText(this.nuevaEmpresa.getNombre());
        this.nomGerente.setText(this.nuevoGerente.getNombre());
    }
    public void createEmpresa(int ruc,String nom,String dir, String correo, String permisoO,String fecha){
        nuevaEmpresa = new Company(ruc,nom,dir,correo,permisoO,fecha);
        nuevaEmpresa.seeInfo();
    }
    
    public void createGerente(int ruc,String nombre, String direccion,String correo){
        nuevoGerente = new Manager(ruc,nombre,direccion,correo,nuevaEmpresa);
        nuevoGerente.seeInfo();
    }
    
    public void delGerente(int aux){
        Administrador vAdministrador = new Administrador(this,true);
        vAdministrador.delgerente(aux);
        vAdministrador.auxiliar = 1;
        vAdministrador.setVisible(true);
    }
    
    public static String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYY");
        return formatoFecha.format(fecha);
    }
    
    public void clearBotones(){
        this.dispensador1.setEnabled(false);
        this.dispensador2.setEnabled(false);
        this.dispensador3.setEnabled(false);
        this.dispensador4.setEnabled(false);
        this.dispensador5.setEnabled(false);
        this.dispensador6.setEnabled(false);
        this.cajeroM1.setEnabled(false);
        this.cajeroM2.setEnabled(false);
        this.cajeroT1.setEnabled(false);
        this.cajeroT2.setEnabled(false);
        this.crearGasolinera.setEnabled(false);
        this.crearMiniMarket.setEnabled(false);
        this.crearTecnicentro.setEnabled(false);
        this.gasolinerService.setEnabled(false);
        this.marketService.setEnabled(false);
        this.tecniService.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel2 = new javax.swing.JPanel();
        nomEmpresa = new javax.swing.JTextField();
        panelPrincipal = new javax.swing.JPanel();
        menuService = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        verificar = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        crearGasolinera = new javax.swing.JButton();
        gasolinerService = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        marketService = new javax.swing.JButton();
        crearMiniMarket = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        crearTecnicentro = new javax.swing.JButton();
        tecniService = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Gasolinera = new javax.swing.JPanel();
        dispensador1 = new javax.swing.JButton();
        dispensador2 = new javax.swing.JButton();
        dispensador3 = new javax.swing.JButton();
        dispensador4 = new javax.swing.JButton();
        dispensador5 = new javax.swing.JButton();
        dispensador6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        MiniMarket = new javax.swing.JPanel();
        cajeroM1 = new javax.swing.JButton();
        cajeroM2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Tecnicentro = new javax.swing.JPanel();
        cajeroT1 = new javax.swing.JButton();
        cajeroT2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        nomGerente = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        nomEmpresa.setEditable(false);
        nomEmpresa.setBackground(new java.awt.Color(0, 102, 102));
        nomEmpresa.setFont(new java.awt.Font("Aharoni", 0, 36)); // NOI18N
        nomEmpresa.setForeground(new java.awt.Color(51, 255, 0));
        nomEmpresa.setText("NOMBRE DE LA EMPRESA");
        nomEmpresa.setBorder(null);
        nomEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nomEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomEmpresaMouseClicked(evt);
            }
        });
        nomEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomEmpresaActionPerformed(evt);
            }
        });

        panelPrincipal.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setText("NUMERO DE SUCURSAL: ");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        verificar.setText("VERIFICAR");
        verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setText("NOMBRE SUCURSAL");

        jLabel3.setText("DIRECCION:");

        jTextField3.setEditable(false);
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jPanel1.setBackground(new java.awt.Color(239, 234, 234));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        crearGasolinera.setText("CREAR GASOLINERA");
        crearGasolinera.setEnabled(false);
        crearGasolinera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearGasolineraActionPerformed(evt);
            }
        });

        gasolinerService.setText("NUEVO SURTIDOR");
        gasolinerService.setEnabled(false);
        gasolinerService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gasolinerServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearGasolinera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(gasolinerService, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearGasolinera)
                    .addComponent(gasolinerService))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setToolTipText("");
        jTextField4.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        marketService.setText("MINIMARKET");
        marketService.setEnabled(false);
        marketService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marketServiceActionPerformed(evt);
            }
        });

        crearMiniMarket.setText("CREAR MINIMARKET");
        crearMiniMarket.setEnabled(false);
        crearMiniMarket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearMiniMarketActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearMiniMarket, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(marketService, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marketService)
                    .addComponent(crearMiniMarket))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        crearTecnicentro.setText("CREAR TECNICENTRO");
        crearTecnicentro.setEnabled(false);
        crearTecnicentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearTecnicentroActionPerformed(evt);
            }
        });

        tecniService.setText("TECNICENTRO");
        tecniService.setEnabled(false);
        tecniService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecniServiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crearTecnicentro)
                .addGap(18, 18, 18)
                .addComponent(tecniService, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearTecnicentro)
                    .addComponent(tecniService))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton5.setText("REPORTE VENTAS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuServiceLayout = new javax.swing.GroupLayout(menuService);
        menuService.setLayout(menuServiceLayout);
        menuServiceLayout.setHorizontalGroup(
            menuServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuServiceLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(menuServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuServiceLayout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(menuServiceLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField3))
                    .addGroup(menuServiceLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuServiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(124, 124, 124))
        );
        menuServiceLayout.setVerticalGroup(
            menuServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuServiceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(menuServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(jButton5)
                .addGap(23, 23, 23))
        );

        dispensador1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/as.png"))); // NOI18N
        dispensador1.setText("DIS 1");
        dispensador1.setBorder(null);
        dispensador1.setBorderPainted(false);
        dispensador1.setContentAreaFilled(false);
        dispensador1.setEnabled(false);
        dispensador1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dispensador1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dispensador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispensador1ActionPerformed(evt);
            }
        });

        dispensador2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/as.png"))); // NOI18N
        dispensador2.setText("DIS 2");
        dispensador2.setBorder(null);
        dispensador2.setBorderPainted(false);
        dispensador2.setContentAreaFilled(false);
        dispensador2.setEnabled(false);
        dispensador2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dispensador2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dispensador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispensador2ActionPerformed(evt);
            }
        });

        dispensador3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/as.png"))); // NOI18N
        dispensador3.setText("DIS 3");
        dispensador3.setBorder(null);
        dispensador3.setBorderPainted(false);
        dispensador3.setContentAreaFilled(false);
        dispensador3.setEnabled(false);
        dispensador3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dispensador3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dispensador3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispensador3ActionPerformed(evt);
            }
        });

        dispensador4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/as.png"))); // NOI18N
        dispensador4.setText("DIS 4");
        dispensador4.setBorder(null);
        dispensador4.setBorderPainted(false);
        dispensador4.setContentAreaFilled(false);
        dispensador4.setEnabled(false);
        dispensador4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dispensador4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dispensador4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispensador4ActionPerformed(evt);
            }
        });

        dispensador5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/as.png"))); // NOI18N
        dispensador5.setText("DIS 5");
        dispensador5.setBorder(null);
        dispensador5.setBorderPainted(false);
        dispensador5.setContentAreaFilled(false);
        dispensador5.setEnabled(false);
        dispensador5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dispensador5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dispensador5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispensador5ActionPerformed(evt);
            }
        });

        dispensador6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/as.png"))); // NOI18N
        dispensador6.setText("DIS 6");
        dispensador6.setBorder(null);
        dispensador6.setBorderPainted(false);
        dispensador6.setContentAreaFilled(false);
        dispensador6.setEnabled(false);
        dispensador6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dispensador6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dispensador6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispensador6ActionPerformed(evt);
            }
        });

        jButton3.setText("GASOLINERA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GasolineraLayout = new javax.swing.GroupLayout(Gasolinera);
        Gasolinera.setLayout(GasolineraLayout);
        GasolineraLayout.setHorizontalGroup(
            GasolineraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GasolineraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(GasolineraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GasolineraLayout.createSequentialGroup()
                        .addGroup(GasolineraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dispensador3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dispensador5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(GasolineraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dispensador6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dispensador4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GasolineraLayout.createSequentialGroup()
                        .addComponent(dispensador1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dispensador2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        GasolineraLayout.setVerticalGroup(
            GasolineraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GasolineraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton3)
                .addGap(31, 31, 31)
                .addGroup(GasolineraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dispensador1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispensador2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(GasolineraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GasolineraLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(dispensador3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GasolineraLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dispensador4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(GasolineraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dispensador5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dispensador6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cajeroM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ASD.png"))); // NOI18N
        cajeroM1.setText("CAJERO 1");
        cajeroM1.setBorder(null);
        cajeroM1.setBorderPainted(false);
        cajeroM1.setContentAreaFilled(false);
        cajeroM1.setEnabled(false);
        cajeroM1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cajeroM1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cajeroM1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajeroM1ActionPerformed(evt);
            }
        });

        cajeroM2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ASD.png"))); // NOI18N
        cajeroM2.setText("CAJERO 2");
        cajeroM2.setBorder(null);
        cajeroM2.setBorderPainted(false);
        cajeroM2.setContentAreaFilled(false);
        cajeroM2.setEnabled(false);
        cajeroM2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cajeroM2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cajeroM2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajeroM2ActionPerformed(evt);
            }
        });

        jButton4.setText("MINI MERCADO");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MiniMarketLayout = new javax.swing.GroupLayout(MiniMarket);
        MiniMarket.setLayout(MiniMarketLayout);
        MiniMarketLayout.setHorizontalGroup(
            MiniMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MiniMarketLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(MiniMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MiniMarketLayout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(MiniMarketLayout.createSequentialGroup()
                        .addComponent(cajeroM1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(cajeroM2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        MiniMarketLayout.setVerticalGroup(
            MiniMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MiniMarketLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(MiniMarketLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajeroM2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(cajeroM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );

        cajeroT1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ASD.png"))); // NOI18N
        cajeroT1.setText("CAJERO 1");
        cajeroT1.setBorder(null);
        cajeroT1.setBorderPainted(false);
        cajeroT1.setContentAreaFilled(false);
        cajeroT1.setEnabled(false);
        cajeroT1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cajeroT1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cajeroT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajeroT1ActionPerformed(evt);
            }
        });

        cajeroT2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ASD.png"))); // NOI18N
        cajeroT2.setText("CAJERO 2");
        cajeroT2.setBorder(null);
        cajeroT2.setBorderPainted(false);
        cajeroT2.setContentAreaFilled(false);
        cajeroT2.setEnabled(false);
        cajeroT2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cajeroT2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cajeroT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajeroT2ActionPerformed(evt);
            }
        });

        jButton6.setText("TECNICENTRO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TecnicentroLayout = new javax.swing.GroupLayout(Tecnicentro);
        Tecnicentro.setLayout(TecnicentroLayout);
        TecnicentroLayout.setHorizontalGroup(
            TecnicentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TecnicentroLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(cajeroT1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(cajeroT2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(TecnicentroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TecnicentroLayout.setVerticalGroup(
            TecnicentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TecnicentroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TecnicentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cajeroT1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(cajeroT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Gasolinera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MiniMarket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tecnicentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Gasolinera, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPrincipalLayout.createSequentialGroup()
                        .addComponent(MiniMarket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tecnicentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(menuService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/construccion-de-la-estacion-de-gas-icono-7807-64.png"))); // NOI18N
        jButton2.setText("GERENTE SUCURSAL");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/cliente-icono-5533-64.png"))); // NOI18N
        jButton1.setText("ADMINISTRADOR");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Picture/ad.png"))); // NOI18N
        jButton13.setText("VER EMPLEADOS");
        jButton13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.setContentAreaFilled(false);
        jButton13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        nomGerente.setFont(new java.awt.Font("Aharoni", 0, 18)); // NOI18N
        nomGerente.setForeground(new java.awt.Color(255, 139, 0));
        nomGerente.setText("NOMBRE GERENTE");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                            .addComponent(nomGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(nomEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(nomGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Opciones");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Gerencia");

        jMenuItem1.setText("Informacion de la Empresa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Informacion del Gerente");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void nomEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomEmpresaActionPerformed

    private void nomEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomEmpresaMouseClicked
        nuevaEmpresa.seeInfo();
    }//GEN-LAST:event_nomEmpresaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Administrador vAdministrador = new Administrador(this,true);
        vAdministrador.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Sucursal vSucursal = new Sucursal(this,true);
        vSucursal.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void dispensador3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispensador3ActionPerformed
        Dispensador open = new Dispensador(this,true);
            open.dispensador_numero = 3;
            open.m = numSucursal;
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_dispensador3ActionPerformed

    private void cajeroM1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajeroM1ActionPerformed
            CajeroMarket open = new CajeroMarket(this,true);
            open.cajero_numero = 1;
            open.m = Integer.parseInt(this.jTextField1.getText());;
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_cajeroM1ActionPerformed

    private void dispensador4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispensador4ActionPerformed
        Dispensador open = new Dispensador(this,true);
            open.dispensador_numero = 4;
            open.m = numSucursal;
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_dispensador4ActionPerformed

    private void dispensador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispensador1ActionPerformed
            Dispensador open = new Dispensador(this,true);
            open.dispensador_numero = 1;
            open.m = numSucursal;
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_dispensador1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarActionPerformed
    int io = Integer.parseInt(JOptionPane.showInputDialog(null, "INGRESE LA CEDULA DEL ADMINISTRADOR DE ESTA SUCURSAL\nO INGRESE LA CEDULA DEL GERENTE","ALTO!!! IDENTIFIQUESE",3));
        if(io == this.nuevoGerente.getSucursales().get(Integer.parseInt(this.jTextField1.getText())-1).getAdministradores().get(0).getRuc() ||  io == this.nuevoGerente.getRuc()){
            
        if( jTextField1.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"INGRESE LA SUCURSAL","ERROR",JOptionPane.ERROR_MESSAGE);   
       }else{
           numSucursal = Integer.parseInt(this.jTextField1.getText());
           int i = Integer.parseInt(this.jTextField1.getText()),m = this.nuevoGerente.getSucursales().size();
            clearBotones();
            
        if(i < 1 || i > m ){
            this.jTextField4.setText("CODIGO INCORRECTO VERIFIQUELO PORFAVOR");
        }else{
            if(this.nuevoGerente.getSucursales().get(i-1).getAdministradores().size() == 0){
                this.jTextField4.setText("LA SUCURSAL NO TIENE ADMINISTRADOR, INGRESE UNO");
            }else{
                this.jTextField4.setText("SUCURSAL LOCALIZADA !! A TRABAJAR !!");
                this.jTextField2.setText(this.nuevoGerente.getSucursales().get(i-1).getNombreSucursal());
                this.jTextField3.setText(this.nuevoGerente.getSucursales().get(i-1).getDireccionSucursal());
                
                //------------------------------GASOLINERA----------------------------------------------------------------------------------------------
                if(this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getGasolinera().size() == 0){
                    this.crearGasolinera.setEnabled(true);                   
                }else{
                    int p = this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().size();
                    this.gasolinerService.setEnabled(true);
                    // .......... miniMercado.............................................
                    int po = this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().size();
                    
                    this.marketService.setEnabled(true);
                    
                    switch(po){
                        case 0: {
                            this.crearMiniMarket.setEnabled(true);
                            this.marketService.setEnabled(false);
                            break;  
                        } case 1: {
                            this.cajeroM1.setEnabled(true);
                            break;
                        } case 2: {
                            this.cajeroM1.setEnabled(true);
                            this.cajeroM2.setEnabled(true);
                            this.marketService.setEnabled(false);
                            break;
                        } 
                    }
                    // .......... Tecnicentro.............................................
                        int pu = this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getTecnicentro().get(0).getCaja().size();
                    
                        this.tecniService.setEnabled(true);
                    
                        switch(pu){
                        case 0: {
                            this.crearTecnicentro.setEnabled(true);
                            this.tecniService.setEnabled(false);
                            break;  
                        } case 1: {
                            this.cajeroT1.setEnabled(true);
                            break;
                        } case 2: {
                            this.cajeroT1.setEnabled(true);
                            this.cajeroT2.setEnabled(true);
                            this.tecniService.setEnabled(false);
                            break;
                        } 
                    }
                    //...............................................................................
                                  
                    switch(p){
                        case 0: {
                            this.crearGasolinera.setEnabled(false);
                            this.crearTecnicentro.setEnabled(false);
                            break;  
                        } case 1: {
                            this.dispensador1.setEnabled(true);
                            break;  
                        } case 2: {
                            this.dispensador1.setEnabled(true);
                            this.dispensador2.setEnabled(true);
                            break;
                        } case 3: {
                            this.dispensador1.setEnabled(true);
                            this.dispensador2.setEnabled(true);
                            this.dispensador3.setEnabled(true);
                            break;
                        } case 4: {
                            this.dispensador1.setEnabled(true);
                            this.dispensador2.setEnabled(true);
                            this.dispensador3.setEnabled(true);
                            this.dispensador4.setEnabled(true);
                            break;
                        } case 5: {
                            this.dispensador1.setEnabled(true);
                            this.dispensador2.setEnabled(true);
                            this.dispensador3.setEnabled(true);
                            this.dispensador4.setEnabled(true);
                            this.dispensador5.setEnabled(true);
                            break;
                        }  case 6: {
                            this.dispensador1.setEnabled(true);
                            this.dispensador2.setEnabled(true);
                            this.dispensador3.setEnabled(true);
                            this.dispensador4.setEnabled(true);
                            this.dispensador5.setEnabled(true);
                            this.dispensador6.setEnabled(true);
                            this.gasolinerService.setEnabled(false);
                            break;
                        }
                    }
                    
                }   
            } 
          }  
       }
        }else{
            JOptionPane.showMessageDialog(null, "IDENTIFICACION INCORRECTA");
        }

    }//GEN-LAST:event_verificarActionPerformed

    private void crearGasolineraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearGasolineraActionPerformed
        
        int i = Integer.parseInt(this.jTextField1.getText());
        
        GasolineraV = new ServiceStation(this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0),fecha());
        this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).createServiceStation(GasolineraV);
        
        this.crearGasolinera.setEnabled(false);
        this.gasolinerService.setEnabled(true);
    }//GEN-LAST:event_crearGasolineraActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void gasolinerServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gasolinerServiceActionPerformed
        int i = Integer.parseInt(this.jTextField1.getText());
        int m = this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().size();
            this.dispensadorV = new Dispenser(this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getGasolinera().get(0),fecha());
            this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getGasolinera().get(0).createDispenser(dispensadorV);
        switch(m){
                        case 0: {
                            this.dispensador1.setEnabled(true);
                            this.crearMiniMarket.setEnabled(true);
                            this.crearTecnicentro.setEnabled(true);
                            break;  
                        } case 1: {
                            this.dispensador2.setEnabled(true);
                            break;
                        } case 2: {
                            this.dispensador3.setEnabled(true);
                            break;
                        } case 3: {
                            this.dispensador4.setEnabled(true);
                            break;
                        } case 4: {
                            this.dispensador5.setEnabled(true);
                            break;
                        }  case 5: {
                            this.dispensador6.setEnabled(true);
                            this.gasolinerService.setEnabled(false);
                            break;
                        }
                    }
        this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getGasolinera().get(0).getDispensadores().get(m).seeInfo();
    }//GEN-LAST:event_gasolinerServiceActionPerformed

    private void dispensador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispensador2ActionPerformed
        Dispensador open = new Dispensador(this,true);
            open.dispensador_numero = 2;
            open.m = numSucursal;
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_dispensador2ActionPerformed

    private void dispensador5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispensador5ActionPerformed
        Dispensador open = new Dispensador(this,true);
            open.dispensador_numero = 5;
            open.m = numSucursal;
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_dispensador5ActionPerformed

    private void dispensador6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispensador6ActionPerformed
        Dispensador open = new Dispensador(this,true);
            open.dispensador_numero = 6;
            open.m = numSucursal;
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_dispensador6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void crearTecnicentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearTecnicentroActionPerformed
        int i = Integer.parseInt(this.jTextField1.getText());
        this.tecniV = new MechanicalService(this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0),fecha());
        this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).createMechanicalService(tecniV);
        this.crearTecnicentro.setEnabled(false);
        this.tecniService.setEnabled(true);
    }//GEN-LAST:event_crearTecnicentroActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
            Reportes open = new Reportes(this,true);
            open.agregar(this.nuevoGerente.getVentaGasolinera().size());
            open.agregarM(this.nuevoGerente.getVentaMarket().size());
            open.agregarT(this.nuevoGerente.getVentaTecnicentro().size());
            open.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9' ) evt.consume();
    }//GEN-LAST:event_jTextField1KeyTyped

    private void crearMiniMarketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearMiniMarketActionPerformed
        int i = Integer.parseInt(this.jTextField1.getText());
        this.tiendaV = new StoreService(this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0),fecha());
        this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).createStoreService(tiendaV);
        this.crearMiniMarket.setEnabled(false);
        this.marketService.setEnabled(true);
        
        
    }//GEN-LAST:event_crearMiniMarketActionPerformed

    private void marketServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marketServiceActionPerformed
        int i = Integer.parseInt(this.jTextField1.getText());
        int m = this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().size();
            this.cajaV = new Box(fecha());
            this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getMinimercado().get(0).createBox(cajaV);           
        switch(m){
                        case 0: {
                            this.cajeroM1.setEnabled(true);
                            break;  
                        } case 1: {
                            this.cajeroM2.setEnabled(true);
                            this.marketService.setEnabled(false);
                            break;
                        }
                    }
        this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getMinimercado().get(0).getCaja().get(m).seeInfo();
    }//GEN-LAST:event_marketServiceActionPerformed

    private void cajeroM2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajeroM2ActionPerformed
            CajeroMarket open = new CajeroMarket(this,true);
            open.cajero_numero = 2;
            open.m = numSucursal;
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_cajeroM2ActionPerformed

    private void cajeroT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajeroT1ActionPerformed
            CajeroTecnicentro open = new CajeroTecnicentro(this,true);
            open.cajero_numero = 1;
            open.m = Integer.parseInt(this.jTextField1.getText());
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_cajeroT1ActionPerformed

    private void cajeroT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajeroT2ActionPerformed
            CajeroTecnicentro open = new CajeroTecnicentro(this,true);
            open.cajero_numero = 2;
            open.m = Integer.parseInt(this.jTextField1.getText());
            open.rellenar();
            open.setVisible(true);
    }//GEN-LAST:event_cajeroT2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tecniServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecniServiceActionPerformed
        int i = Integer.parseInt(this.jTextField1.getText());
        int m = this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getTecnicentro().get(0).getCaja().size();
            this.cajaV = new Box(fecha());
            this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getTecnicentro().get(0).createBox(cajaV);           
        switch(m){
                        case 0: {
                            this.cajeroT1.setEnabled(true);
                            break;  
                        } case 1: {
                            this.cajeroT2.setEnabled(true);
                            this.tecniService.setEnabled(false);
                            break;
                        }
                    }
        this.nuevoGerente.getSucursales().get(i-1).getAdministradores().get(0).getTecnicentro().get(0).getCaja().get(m).seeInfo();
    }//GEN-LAST:event_tecniServiceActionPerformed
    public void reportesDispensador(int n,int dispensador,int m){
        Reportes open = new Reportes(this,true);
        open.agregarDispensador(n, dispensador, m);
        open.setVisible(true);
    }
    public void reportesCajeroM(int n,int dispensador,int m){
        Reportes open = new Reportes(this,true);
        open.agregarCajeroM(n, dispensador, m);
        open.setVisible(true);
    }
    public void reportesCajeroT(int n,int dispensador,int m){ /// OJO AUN NO ESTA MODIFICADO
        Reportes open = new Reportes(this,true);
        open.agregarCajeroT(n, dispensador, m);
        open.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Gasolinera;
    private javax.swing.JPanel MiniMarket;
    private javax.swing.JPanel Tecnicentro;
    private javax.swing.JButton cajeroM1;
    private javax.swing.JButton cajeroM2;
    private javax.swing.JButton cajeroT1;
    private javax.swing.JButton cajeroT2;
    private javax.swing.JButton crearGasolinera;
    private javax.swing.JButton crearMiniMarket;
    private javax.swing.JButton crearTecnicentro;
    private javax.swing.JButton dispensador1;
    private javax.swing.JButton dispensador2;
    private javax.swing.JButton dispensador3;
    private javax.swing.JButton dispensador4;
    private javax.swing.JButton dispensador5;
    private javax.swing.JButton dispensador6;
    private javax.swing.JButton gasolinerService;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton marketService;
    private javax.swing.JPanel menuService;
    private javax.swing.JTextField nomEmpresa;
    private javax.swing.JLabel nomGerente;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JButton tecniService;
    private javax.swing.JButton verificar;
    // End of variables declaration//GEN-END:variables
}
