/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.encuestas.ec.views;

import com.encuestas.ec.bo.ObjectBo;
import com.encuestas.ec.dao.ObjectDao;
import com.encuestas.ec.entity.Encuesta;
import com.encuestas.ec.entity.Pregunta;
import com.encuestas.ec.entity.RespuestaTexto;
import com.encuestas.ec.entity.TextPrompt;
import com.encuestas.ec.entity.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Freddie
 */
public class EncuestaFrame extends javax.swing.JFrame {

    Encuesta encuesta = new Encuesta();
    Pregunta pregunta = new Pregunta();
    RespuestaTexto respuesta = new RespuestaTexto();
    Usuario usuario = new Usuario();
    ObjectBo obo = new ObjectBo();
    ObjectDao objeto = new ObjectDao();
    String mensaje = "";
    int banderaGuardar = 0;

    public EncuestaFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        TextPrompt placeholder = new TextPrompt("Nombre de Encuesta", txtNombreE);
        placeholder = new TextPrompt("Descripcion de Encuesta", txtDescripcionE);

    }

    public EncuestaFrame(int idEncues, String nombreE, String descripcioE) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        txtDescripcionE.setText(descripcioE);
        txtNombreE.setText(nombreE);
        this.banderaGuardar = idEncues;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        txtNombreE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionE = new javax.swing.JTextArea();
        cbxTipoE = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAceptarE = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNombreE.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N

        txtDescripcionE.setColumns(20);
        txtDescripcionE.setRows(5);
        jScrollPane1.setViewportView(txtDescripcionE);

        cbxTipoE.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        cbxTipoE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARKETING", "TALLER", "SEGURIDAD DE DATOS", "EFICIENCIA EN EL CONTROL DE ACTIVOS" }));

        jLabel1.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        jLabel1.setText("Tipo de Encuesta:");

        btnAceptarE.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        btnAceptarE.setText("Aceptar");
        btnAceptarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarEActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        jLabel3.setText("Ingreso de Encuesta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cbxTipoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(btnAceptarE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar)))
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(228, 228, 228))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarE)
                    .addComponent(btnCancelar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarEActionPerformed
        obo.confirmarCambiosObjeto();
        if (txtDescripcionE.getText().isEmpty() || txtNombreE.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
        } else {
            int tipoEncuesta = cbxTipoE.getSelectedIndex() + 1;
            System.out.println(tipoEncuesta);
            encuesta.setIDENCUESTA(findIdEncuesta());//obo.getMaxID(encuesta));
            encuesta.setNOMBRE(txtNombreE.getText());
            encuesta.setDESCRIPCION(txtDescripcionE.getText());
            encuesta.setIDTIPOENCUESTA(tipoEncuesta);
            String mensaje;
            if (this.banderaGuardar != 0) {
                mensaje = obo.modificarObjeto(encuesta);
            } else {
                mensaje = obo.agregarObjeto(encuesta);
                //                mensaje = obo.agregarObjetoE(encuesta,"0104496765");

            }
            if (mensaje == "1") {
                this.setVisible(false);
                new PreguntaFrame(encuesta).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Error: " + mensaje);
            }

    }//GEN-LAST:event_btnAceptarEActionPerformed
    }

    private int findIdEncuesta() {
        if (this.banderaGuardar != 0) {
            return banderaGuardar;
        } else {
            return obo.getMaxID(encuesta);
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        obo.quitarCambiosObjeto();
        Inicio inicio = new Inicio();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarE;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbxTipoE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcionE;
    private javax.swing.JTextField txtNombreE;
    // End of variables declaration//GEN-END:variables
}
