/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.encuestas.ec.views;

import com.encuestas.ec.bo.ObjectBo;

/**
 *
 * @author Freddie
 */
public class Inicio extends javax.swing.JFrame {

    ObjectBo obo = new ObjectBo();

    public Inicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        obo.deshabilitarCambiosObjeto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCrearE = new javax.swing.JButton();
        btnResponderE = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnResponderE1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearE.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        btnCrearE.setText("Encuesta - Administrador");
        btnCrearE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 270, -1));

        btnResponderE.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        btnResponderE.setText("Consultas Genericas");
        btnResponderE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderEActionPerformed(evt);
            }
        });
        jPanel1.add(btnResponderE, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 270, -1));

        jButton1.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        jButton1.setText("Revisar Actividad");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 270, -1));

        btnResponderE1.setFont(new java.awt.Font("Helvetica World", 0, 11)); // NOI18N
        btnResponderE1.setText("Encuesta-Usuario");
        btnResponderE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResponderE1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnResponderE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEActionPerformed
//        EncuestaFrame ven = new EncuestaFrame();
//        ven.setVisible(true);
        EncuestaSeleccionAdministrador eadmin = new EncuestaSeleccionAdministrador();
        eadmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCrearEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ActividadUsuariosFrame auser = new ActividadUsuariosFrame();
        auser.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnResponderEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderEActionPerformed
        EncuestasConsultas rf = new EncuestasConsultas();
        rf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnResponderEActionPerformed

    private void btnResponderE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResponderE1ActionPerformed
        EncuestaSeleccionUsuario rf= new EncuestaSeleccionUsuario();
        rf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnResponderE1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearE;
    private javax.swing.JButton btnResponderE;
    private javax.swing.JButton btnResponderE1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
