<ncl id="myNCLDocID" xmlns="http://www.ncl.org.br/NCL3.0/EDTVProfile">
	<head>
		<regionBase id="regionBase0">
			<region height="50.83%" id="region0" left="0.00%" top="49.17%" width="100.00%" zIndex="1">
			</region>
		</regionBase>
		<descriptorBase id="db0">
			<descriptor id="d0" region="region0">
			</descriptor>
		</descriptorBase>
	</head>
	<body id="myBodyID">
		<media descriptor="d0" id="m0" src="background.jpg">
		</media>
		<port component="m0" id="p0">
		</port>
	</body>
</ncl>
