rollback
SET AUTO[COMMIT] {OFF};
select * from encuesta;
select * from pregunta;
select * from usuario;
select * from pregunta order by idpregunta;
truncate table usuario;
truncate table encuesta;
truncate table opciones;
truncate table pregunta;
desc usuario;
desc PREGUNTA;

SELECT P.IDPREGUNTA,P.PREGUNTA,P.IDENCUESTA,O.IDSELECCION,O.NOMBREOPCION FROM PREGUNTA P, OPCIONES O WHERE (P.IDENCUESTA=2);

SELECT P.IDPREGUNTA,P.PREGUNTA,P.IDENCUESTA,O.IDSELECCION,O.NOMBREOPCION FROM PREGUNTA P,OPCIONES O WHERE (P.IDENCUESTA=1 AND P.IDTIPORESPUESTA=2);
SELECT * FROM PREGUNTA P WHERE (P.IDENCUESTA=1 AND P.IDTIPORESPUESTA=1);
SELECT P.IDPREGUNTA,P.PREGUNTA,P.IDTIPORESPUESTA,O.IDSELECCION,O.NOMBREOPCION FROM PREGUNTA P, OPCIONES O WHERE (P.IDENCUESTA=3 AND P.IDTIPORESPUESTA=2);
SELECT P.IDPREGUNTA,P.PREGUNTA,P.IDTIPORESPUESTA FROM PREGUNTA P, OPCIONES O WHERE (P.IDENCUESTA=1 AND P.IDTIPORESPUESTA=2);
SELECT Distinct P.IDPREGUNTA,P.PREGUNTA,P.IDTIPORESPUESTA,p.idencuesta pidencuesta,o.idencuesta oidencuesta FROM PREGUNTA P, OPCIONES O WHERE (P.IDENCUESTA=2);
SELECT P.IDPREGUNTA,P.PREGUNTA,P.IDTIPORESPUESTA,p.idencuesta pidencuesta,o.idencuesta oidencuesta FROM PREGUNTA P, OPCIONES O WHERE (P.IDENCUESTA=3);

--SELECCIONAR OPCIONES
SELECT DISTINCT
PE.IDPREGUNTA,PE.PREGUNTA,PE.IDTIPORESPUESTA,PE.idencuesta pidencuesta,o.idencuesta oidencuesta 
FROM PREGUNTA PE 
INNER JOIN OPCIONES O ON O.idencuesta=PE.idencuesta AND PE.IDENCUESTA=3 AND PE.IDTIPORESPUESTA=2;
--preguntas texto
SELECT PE.IDPREGUNTA,PE.PREGUNTA,PE.IDTIPORESPUESTA,PE.idencuesta pidencuesta 
FROM PREGUNTA PE
WHERE PE.IDENCUESTA = 3 AND PE.IDTIPORESPUESTA=1;
SELECT  o.idopcion,PE.IDPREGUNTA,O.NOMBREOPCION,PE.IDTIPORESPUESTA,PE.idencuesta,o.idencuesta  FROM PREGUNTA PE INNER JOIN OPCIONES O ON O.idencuesta=PE.idencuesta AND PE.IDENCUESTA=3 AND PE.IDTIPORESPUESTA=2;
SELECT * FROM OPCIONES;
SELECT * FROM PREGUNTA;

SELECT PE.IDPREGUNTA,O.NOMBREOPCION,PE.IDTIPORESPUESTA,PE.idencuesta pidencuesta  FROM PREGUNTA PE WHERE (PE.IDENCUESTA = 3 AND PE.IDTIPORESPUESTA=1);

desc OPCIONES;
desc ejemplar;
desc alumnoejemplar;
desc edicion;
desc libro;
desc autor;
desc editorial;


select * from usuario;



desc PREGUNTA;

truncate usuario;
 
USE ADMINISTRADOR;
 

 

SELECT * FROM ENCUESTA;
SELECT * FROM RESPUESTAOPCIONMULTIPLE;

DESC PREGUNTA;
DESC RESPUESTATEXTO;

SELECT  o.IDENCUESTA,o.IDPREGUNTA,en.pregunta,o.idrespuestatexto,o.respuesta FROM (PREGUNTA en) INNER JOIN RESPUESTATEXTO o ON o.idencuesta=en.IDENCUESTA AND o.idusuario='0104444444';

SELECT  DISTINCT O.IDENCUESTA,O.IDPREGUNTA,en.pregunta,o.idrespuestaopcionmultiple,o.idopcion FROM (PREGUNTA en) INNER JOIN RESPUESTAOPCIONMULTIPLE O ON O.idencuesta=en.idencuesta AND o.idusuario='0104444444';

SELECT  O.idencuesta,en.nombre  FROM (ENCUESTA en) INNER JOIN RESPUESTAOPCIONMULTIPLE O ON O.IDENCUESTA=EN.IDENCUESTA AND O.IDUSUARIO='cx';
SELECT  O.idencuesta,en.nombre  FROM (ENCUESTA en) INNER JOIN RESPUESTAOPCIONMULTIPLE O ON O.IDENCUESTA=EN.IDENCUESTA AND O.IDUSUARIO='0104496765';

SELECT  o.IDENCUESTA,o.IDPREGUNTA,en.pregunta,o.idrespuestatexto,o.respuesta  FROM  (PREGUNTA en)  INNER JOIN RESPUESTATEXTO O ON O.IDENCUESTA=EN.IDENCUESTA AND O.IDUSUARIO='0104444444';